#ifndef LIMITS_H
#define LIMITS_H

#define CAPTURE_SIZE 20274

#define MAX_PACKETS_PER_MSG 32
#define PAYLOAD_MAX_BUFFER 128000


#define MAX_POOL_SIZE 32
#define SLEEP_IN_MONITOR
#define MONITOR_PERIOD 5
#define MESSAGE_TIMEOUT 100

#endif

